import secrets
import string
import os
import sys
from pathlib import Path
from datetime import datetime
 
ENV_PATH = Path(__file__).parent.parent / ".env"

def _random_password(length: int = 32) -> str:
    """Alphanumeric + safe symbols, no shell-special chars."""
    alphabet = string.ascii_letters + string.digits + "!@#%^&*-_=+"
    return "".join(secrets.choice(alphabet) for _ in range(length))
 
 
def _api_key(length: int = 48) -> str:
    """URL-safe base64 token."""
    return secrets.token_urlsafe(length)
 
 
def generate() -> dict[str, str]:
    return {
        "API_KEY": _api_key(),
        "GRAFANA_ADMIN_USER": "admin",
        "GRAFANA_ADMIN_PASSWORD": _random_password(24),
        "GRAFANA_SECRET_KEY": _api_key(32),
    }

def write_env(values: dict[str, str], path: Path) -> None:
    if path.exists():
        backup = path.with_suffix(f".env.bak.{datetime.now().strftime('%Y%m%d_%H%M%S')}")
        path.rename(backup)
        print(f"    Previous .env backed up to {backup.name}")
 
    lines = [
        "# ─────────────────────────────────────────────────────────────────",
        f"# Auto-generated by API on {datetime.now().isoformat(timespec='seconds')}",
        "# DO NOT commit this file to version control!",
        "# ─────────────────────────────────────────────────────────────────",
        "",
        "# API",
        f'API_KEY={values["API_KEY"]}',
        "",
        "# Grafana",
        f'GRAFANA_ADMIN_USER={values["GRAFANA_ADMIN_USER"]}',
        f'GRAFANA_ADMIN_PASSWORD={values["GRAFANA_ADMIN_PASSWORD"]}',
        f'GRAFANA_SECRET_KEY={values["GRAFANA_SECRET_KEY"]}',
        "",
        "# Domain (leave blank for IP/self-signed mode)",
        "DOMAIN=",
        "",
        "# Ports exposed on the host",
        "NGINX_HTTP_PORT=80",
        "NGINX_HTTPS_PORT=443",
    ]
    path.write_text("\n".join(lines) + "\n")

def main() -> None:
    print("\n🔐 Generating secure credentials …")
    values = generate()
    write_env(values, ENV_PATH)
 
    print(f"\n[!]  .env written to: {ENV_PATH} [!]")
    print("\n┌─────────────────────────────────────────────────────┐")
    print("│              GENERATED CREDENTIALS                 │")
    print("├─────────────────────────────────────────────────────┤")
    print(f"│  API Key        : {values['API_KEY'][:20]}…  │")
    print(f"│  Grafana user   : {values['GRAFANA_ADMIN_USER']:<32} │")
    print(f"│  Grafana pass   : {values['GRAFANA_ADMIN_PASSWORD']:<32} │")
    print("└─────────────────────────────────────────────────────┘")
    print("\n[!]  Save the Grafana password — it won't be shown again. [!]\n")
 
 
if __name__ == "__main__":
    main()